#! /usr/bin/env Rscript

# Get DNase- or ATAC-seq count matrices for the candidate sites,
# then normalize, bin and transform the counts
library(optparse)
library(TOP)
library(data.table)

# ================ Process the command-line arguments ================
option_list <- list(
  make_option('--sites', action='store', default=NULL, type='character',
              help='Filename for candidate sites.'),
  make_option('--genomecount_dir', action='store', default=NULL, type='character',
              help='Directory for genome counts'),
  make_option('--genomecount_name', action='store', default='samtools', type='character',
              help='File prefix for genome counts.'),
  make_option("--idxstats", action="store", default=NULL, type='character',
              help="The idxstats file generated by samtools."),
  make_option("--bin", action="store", default='M5', type='character',
              help="MILLIPEDE binning scheme. [default: %default]"),
  make_option("--ref_size", action="store", default=1e8, type='integer',
              help="Reference library size. [default: %default]"),
  make_option("--transform", action="store", default='asinh', type='character',
              help="Type of transform for binned counts. [default: %default]"),
  make_option('--outdir', action='store', default=NULL, type='character',
              help='Output directory.'),
  make_option('--outname', action='store', default=NULL, type='character',
              help='Output filename prefix.'),
  make_option('--bwtool', action='store', default='bwtool', type='character',
              help='Path to bwtool executable.')
)

opt <- parse_args(OptionParser(option_list=option_list))
sites_file             <- opt$sites
genomecount_dir        <- opt$genomecount_dir
genomecount_name       <- opt$genomecount_name
idxstats_file          <- opt$idxstats
bin_method             <- opt$bin
ref_size               <- opt$ref_size
transform              <- opt$transform
outdir                 <- opt$outdir
outname                <- opt$outname
bwtool_path            <- opt$bwtool

# ================ Get count matrices for candidate sites ================

if(!dir.exists(outdir)){
  dir.create(outdir, showWarnings = F, recursive = T)
}

sites_counts_matrix_file <- file.path(outdir, paste0(outname, '.countmatrix.rds'))
sites_bins_file <- file.path(outdir, paste0(outname, '.', bin_method, '_bins.rds'))

if( !file.exists(sites_file) || file.size(sites_file) == 0 ){
  cat(paste(sites_file, 'file does not exist or is empty. \n'))
  # create empty files for snakemake downstream pipeline.
  res <- file.create(sites_counts_matrix_file)
  res <- file.create(sites_bins_file)
}else{
  # Load candidate sites
  cat('Load candidate sites...\n')
  sites.df <- as.data.frame(fread(sites_file))

  # Get counts matrix for candidate sites
  cat('Get counts matrix for candidate sites...\n')
  sites_counts.mat <- get_sites_counts(sites.df,
                                       genomecount_dir=genomecount_dir,
                                       genomecount_name=genomecount_name,
                                       tmpdir=outdir,
                                       bwtool_path=bwtool_path)
  saveRDS(sites_counts.mat, sites_counts_matrix_file)
  cat('Read counts matrix saved at:', sites_counts_matrix_file, '\n')

  # Normalize, bin and transform counts
  cat('Normalize, bin and transform counts...\n')
  bins.df <- normalize_bin_transform_counts(sites_counts.mat,
                                            idxstats_file=idxstats_file,
                                            ref_size=ref_size,
                                            bin_method=bin_method,
                                            transform=transform)

  sites_bins.df <- data.frame(sites.df, bins.df)
  colnames(sites_bins.df) <- c(colnames(sites.df), paste0('bin', 1:ncol(bins.df)))

  saveRDS(sites_bins.df, sites_bins_file)
  cat('Done. Binned result saved at:', sites_bins_file, '\n')

}
