#! /usr/bin/env Rscript

# R script to normalize, bin DNase (or ATAC) data with MILLIPEDE binning scheme
# and transform (asinh or log2) DNase (or ATAC) counts
library(optparse)
library(TOP)

# ================ Process the command-line arguments ================
option_list <- list(
  make_option("--counts", action="store", default=NULL, type='character',
              help="Filename of sites count matrix."),
  make_option("--idxstats", action="store", default=NULL, type='character',
              help="The idxstats file generated by samtools."),
  make_option("--bin", action="store", default='M5', type='character',
              help="MILLIPEDE binning scheme. [default: %default]"),
  make_option("--refsize", action="store", default=1e8, type='integer',
              help="Reference library size. [default: %default]"),
  make_option("--transform", action="store", default='asinh', type='character',
              help="Type of transform for binned counts. [default: %default]"),
  make_option('--outdir', action='store', default=NULL, type='character',
              help='Output directory.'),
  make_option('--outname', action='store', default=NULL, type='character',
              help='Output filename prefix.')
)

opt <- parse_args(OptionParser(option_list=option_list))
sites_counts_file    <- opt$counts
idxstats_file        <- opt$idxstats
bin_method           <- opt$bin
ref_size             <- opt$refsize
transform            <- opt$transform
outdir               <- opt$outdir
outname              <- opt$outname


# ================ Normalize, binning and transform counts ================

if(!dir.exists(outdir)){
  dir.create(outdir, showWarnings = FALSE, recursive = TRUE)
}

bins_file <- file.path(outdir, paste0(outname, '.', bin_method, '_bins.rds'))

if( !file.exists(sites_counts_file) || file.size(sites_counts_file) == 0){
  cat(paste(sites_counts_file, 'file does not exist or is empty.\n'))
  res <- file.create(bins_file) # create an empty file for snakemake downstream pipeline.
}else{
  sites.df <- as.data.frame(fread(sites_file))

  sites_counts.mat <- readRDS(sites_counts_file)

  bins.df <- normalize_bin_transform_counts(sites_counts.mat,
                                            idxstats_file=idxstats_file,
                                            ref_size=ref_size,
                                            bin_method=bin_method,
                                            transform=transform)

  sites_bins.df <- data.frame(sites.df, bins.df)
  colnames(sites_bins.df) <- c(colnames(sites.df), paste0('bin', 1:ncol(bins.df)))

  saveRDS(sites_bins.df, bins_file)

}
